# Generated by Django 5.1.1 on 2024-09-12 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_remove_phone_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='created_by',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
