# Generated by Django 5.1.1 on 2024-09-12 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0008_phone_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='created_by',
        ),
    ]
