# Generated by Django 5.1.1 on 2024-09-12 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0009_remove_phone_created_by'),
    ]

    operations = [
        migrations.DeleteModel(
            name='phone',
        ),
    ]
