# Generated by Django 5.1.1 on 2024-09-12 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0012_phone_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='author',
        ),
    ]
